name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: poetry install --all-extras

    - name: Run tests
      run: poetry run pytest --cov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: success()
      with:
        fail_ci_if_error: true  # Optional, fails the job if Codecov upload fails
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Build project
      if: success()
      run: poetry build

    - name: Publish to PyPI
      if: success()
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
        poetry publish
